name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  compose-file:
    description: 'Path to the docker-compose file'
    required: true

  secrets:
    description: "Docker secrets to create during the stack"
    required: false

  stack-name:
    description: 'Name of the stack to deploy'
    required: true

  ssh-user-at-host:
    description: 'User@host to connect to'
    required: true
  
  ssh-port:
    description: "Port to connect to with SSH"
    required: false
    default: "22"

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
