version: "3.9"

services:
  server:
    build:
      dockerfile: docker/server.Dockerfile
    command: ""
    privileged: true
    cgroup: host
    ports:
      - 127.0.0.1:2222:22
      - 127.0.0.1:8888:8080
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
